# Generated by Django 5.2.5 on 2025-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userkey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
