# Generated by Django 5.2.5 on 2025-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_id_alter_noteitem_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteitem',
            options={'ordering': ['permission']},
        ),
        migrations.AddField(
            model_name='noteitem',
            name='permission',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('O', 'Owner')], default='R', max_length=1),
        ),
    ]
