# Generated by Django 5.2.5 on 2025-08-30 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_noteitem_options_noteitem_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_KEY_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noteitem', to=settings.AUTH_USER_KEY_MODEL),
        ),
    ]
