# Generated by Django 5.2.5 on 2025-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_noteitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.BinaryField(),
        ),
    ]
