# Generated by Django 5.2.5 on 2025-08-30 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_body'),
        migrations.swappable_dependency(settings.AUTH_USER_KEY_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteitem',
            old_name='encryption_key',
            new_name='encrypted_symmetric_key',
        ),
        migrations.AlterUniqueTogether(
            name='noteitem',
            unique_together={('note', 'user')},
        ),
    ]
