# Generated by Django 5.2.5 on 2025-08-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_encryption_key_noteitem_encrypted_symmetric_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='encrypted_symmetric_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
