# Generated by Django 5.2.5 on 2025-08-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_noteitem_encrypted_symmetric_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='encrypted_symmetric_key',
            field=models.BinaryField(blank=True, db_column='encrypted_symmetric_key', null=True),
        ),
        migrations.RenameField(
            model_name='noteitem',
            old_name='encrypted_symmetric_key',
            new_name='encryption_key',
        ),
    ]
