# Generated by Django 5.2.5 on 2025-08-31 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_noteitem_encrypted_symmetric_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_KEY_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='noteitem',
            old_name='user',
            new_name='user_key',
        ),
        migrations.AlterUniqueTogether(
            name='noteitem',
            unique_together={('note', 'user_key')},
        ),
    ]
