# Generated by Django 5.2.5 on 2025-09-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_rename_user_noteitem_user_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='permission',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('S', 'Share'), ('O', 'Owner')], default='R', max_length=1),
        ),
    ]
